### ISSUE TITLE
Unwinnable game condition, buried book of the dead 

### ISSUE THREAD

**Issue by gebulmer** [hyvanmielenpelit/GnollHack#1599] opened 2021-06-11 15:03 UTC
Hi,

I killed the wizard over the moat and then read scroll of earth to fill in the moat to attempt to dig it out
Unfortunately I cannot dig it out, is there any way to retrieve the book of the dead?

This is for a junethack game on the EU gnollhack server

**Comment by TommiGustafsson-HMP** [comment] 2021-06-11 15:31
@janne-hmp Can look at this and hotfix.

**Comment by janne-hmp** [comment] 2021-06-11 17:20
This has been now fixed. The servers have been updated, and you can now load the saved game and dig the papyrus spellbook up. There were three different bugs, one of which caused the Book to be buried in the first place and two other logical ones (a variable on the wrong side of parentheses, caused by an updated trap system) that caused the floor to be completely undiggable.

**Closed by janne-hmp** 2021-06-11 17:20 UTC
