### ISSUE TITLE
clone_mon fails to copy mextra, which can lead to immediate crashes

### ISSUE THREAD

**Issue by demogorgon22** [hyvanmielenpelit/GnollHack#647] opened 2020-01-28 19:09 UTC
## To replicate:
- Don't have cold resistance
- Get a god to summon a minion on you.
- Turn on mon poly control and turn it into a blue jelly.
- Hit it until it clones
- Receive and immediate crash.
## Why is this caused?
Currently, clone_mon just 0s out mextra. If the base monster has isminion set, so will the cloned one, but it won't have an mextra, or an mextra->emin, as all minions are assumed to. This will cause a crash immediately in set_malign as it checks if its a minion, and if it is, goes for mextra->emin which doesn't exist because clone_mon failed to copy it.

**Comment by janne-hmp** [comment] 2020-01-28 22:38
Thanks for the report. However, the current code shows that clone_mon does actually copy emin and all the other relevant mextra data fields, so the scenario you describe should not happen. On line 1704 it says:
`        if (mon->isminion) 
		{
            newemin(m2);
            if (EMIN(mon))
                *(EMIN(m2)) = *(EMIN(mon));
        }
`
Can you please elaborate what you mean there?

**Comment by janne-hmp** [comment] 2020-01-28 23:56
Closed as spurious.

**Comment by AmyBSOD** [comment] 2020-01-29 21:04
*erm* [https://abload.de/img/guysfixyourshitpleasefpj0j.png](crash screenshot)

You should:
1. not dismiss players' bug reports just like that
2. get on the IRC more often because that's where all the other variant developers hang out
3. improve the style of your commits by not packing several unrelated changes into one commit, stopping to clog up commits with updates to date.h (that file, along with pm.h and onames.h, doesn't belong in the repo) and, if your variant is hosted on a public server, testing whether your changes are savebreaking.

Sorry about that. I hope that in the foreseeable future you can iron out the problems with Gnollhack and make it truly ready for the public servers, but I fear that right now you still have some work to do until you reach that point.

Best regards,
Amy Bluescreenofdeath

**Comment by janne-hmp** [comment] 2020-01-29 22:12
Hi Amy, thanks for the feedback. I do not generally dismiss player feedback, but after a proper review of the related code, I deemed that the described scenario should not happen in any case, based on the actual clone_mon code. What was said as the reason for bug did not correspond to the actual code in clone_mon, which does copy emin properly. We received no explanation from the report maker on the apparent discrepancy between what he wrote and what there is in the code. The situation is extremely remote, and the original NetHack clone_mon code should work exactly as intended even in that remote scenario. Therefore, this report seemed dubious to me, also given that the other crash reports suggested by the same player were incapable of creating real crashes.

**Comment by janne-hmp** [comment] 2020-01-29 23:08
I checked the original NetHack code again, and it may indeed potentially cause a crash. It should set isminion to zero if the m2 is not tame (which may happen randomly due to the code inserted to the function before checking for tameness). This is a bug from NetHack 3.6.2 and nothing to do with us, but clearly we can fix it. It would be helpful to have the report maker’s comments here, or his proposal how to fix the issue, instead elsewhere to avoid any misunderstandings.

**Comment by janne-hmp** [comment] 2020-01-29 23:17
Fixed. Apologies for the initial harsh treatment of this issue. Please post possible disagreements here, and ideally make a pull request to suggest a correction to code to avoid any misunderstandings.

**Closed by janne-hmp** 2020-01-29 23:17 UTC

**Comment by AmyBSOD** [comment] 2020-01-29 23:20
Well I can only speak for myself: if you get on the IRC, you can talk to Gnollhack players in real time, which could potentially avoid many such misunderstandings ;) Anyway, thanks for fixing the crash.

**Comment by janne-hmp** [comment] 2020-01-29 23:30
Sure. I happen to have an unusually busy schedule this week until Friday with a very limited chance to be on IRC, but from Saturday onwards I'll be back to my normal schedule with much better possibility to chat on IRC.

**Comment by bhaak** [comment] 2020-01-30 11:34
That's the problem with forks, you inherit the bugs from upstream.
The first thing to do would be to look if it has been fixed in the current NetHack 3.7 branch or maybe even in 3.6.
